[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -ra

norecursedirs =
    docker
    .git
    .pytest_cache
    __pycache__
    .venv
    venv

