x-airflow-common: &airflow-common
  build:
    context: ../../
    dockerfile: docker/airflow/Dockerfile

  env_file:
    - ../../.env

  environment:
    AIRFLOW_UID: ${AIRFLOW_UID}
    AIRFLOW_HOME: ${AIRFLOW_HOME}
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: ${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION}
    AIRFLOW__CORE__DEFAULT_TIMEZONE: ${AIRFLOW__CORE__DEFAULT_TIMEZONE}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CELERY__BROKER_URL: ${AIRFLOW__CELERY__BROKER_URL}
    AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW__CELERY__RESULT_BACKEND}

  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../airflow/logs:/opt/airflow/logs
    - ../airflow/plugins:/opt/airflow/plugins
    - ../airflow/config:/opt/airflow/config

  depends_on:
    postgres:
      condition: service_started

    redis:
      condition: service_healthy

  networks:
    - dataforge-network

services:

  postgres:
    image: postgres:17

    container_name: dataforge-postgres

    restart: unless-stopped

    env_file:
      - ../../.env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - dataforge-network

  redis:
    image: redis:8

    container_name: dataforge-redis

    restart: unless-stopped

    command: redis-server /usr/local/etc/redis/redis.conf

    ports:
      - "6379:6379"

    volumes:
      - ../../docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - dataforge-network

  airflow-init:
    <<: *airflow-common

    container_name: dataforge-airflow-init

    command: >
      bash -c "
      airflow db migrate &&
      airflow standalone
      "

volumes:
  postgres_data:
  redis_data:

networks:
  dataforge-network:
    driver: bridge
