##############################################
# DataForge Redis Configuration
##############################################

# Network
bind 0.0.0.0
protected-mode no
port 6379

# Persistence
appendonly yes
appendfilename "appendonly.aof"

# Logging
loglevel notice

# Memory
maxmemory-policy allkeys-lru

